name: 18.3 - Reusable Workflows
run-name: 18 - 3 - Reusable Workflows

on:
    workflow_dispatch:

jobs:
    deploy:
        uses: ./.github/workflows/18-1-reusable-workflows.yml
        with:
            target-drectory: dummy-dir
    e2e-tests:
        # Reuse the workflow defined in the same repository
        # uses: <owner>/<repo>/.github/workflows/<workflow_name>@<version>
        uses: gh-actions-master-class/github-actions-course-exmaple-e2e/.github/workflows/e2e.yml@main
